CREATE TABLE OPENAI_PROPERTIES
(
    ID  BIGINT AUTO_INCREMENT,
    `OPENAI_KEY` VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE OPENAI_PROPERTIES COMMENT 'openai配置类';

ALTER TABLE OPENAI_PROPERTIES
    MODIFY COLUMN `OPENAI_KEY` VARCHAR(64) NOT NULL COMMENT 'openai的key';

CREATE TABLE TRANSLATE_FILES
(
    FILE_ID    INTEGER AUTO_INCREMENT,
    PROJECT_ID INTEGER,
    FILE_NAME  VARCHAR(255),
    PRIMARY KEY (FILE_ID)
);

ALTER TABLE TRANSLATE_FILES COMMENT '文件表';

ALTER TABLE TRANSLATE_FILES
    MODIFY COLUMN PROJECT_ID INTEGER COMMENT '项目id';

ALTER TABLE TRANSLATE_FILES
    MODIFY COLUMN FILE_NAME VARCHAR(255) COMMENT '文件名';

CREATE TABLE TRANSLATE_PROJECTS
(
    PROJECT_ID   INTEGER AUTO_INCREMENT,
    PROJECT_NAME VARCHAR(255),
    PRIMARY KEY (PROJECT_ID)
);

ALTER TABLE TRANSLATE_PROJECTS COMMENT '项目表';

ALTER TABLE TRANSLATE_PROJECTS
    MODIFY COLUMN PROJECT_NAME VARCHAR(255) COMMENT '项目名称';

CREATE TABLE TRANSLATIONS
(
    ID               BIGINT AUTO_INCREMENT,
    PROJECT_ID       INTEGER,
    FILE_ID          INTEGER,
    ORIGINAL_TEXT    VARCHAR(8000) NOT NULL,
    TRANSLATION_TEXT VARCHAR(8000),
    SEQUENCE         INTEGER,
    PRIMARY KEY (ID)
);

ALTER TABLE TRANSLATIONS COMMENT 'json翻译表';

ALTER TABLE TRANSLATIONS
    MODIFY COLUMN ORIGINAL_TEXT VARCHAR(8000) NOT NULL COMMENT '原文';

ALTER TABLE TRANSLATIONS
    MODIFY COLUMN TRANSLATION_TEXT VARCHAR(8000) COMMENT '译文';

ALTER TABLE TRANSLATIONS
    MODIFY COLUMN SEQUENCE INTEGER COMMENT '句子序列';
