spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://192.168.123.106:33061/translate?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
