spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:hsqldb:file:db/translate;shutdown=true
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  sql:
    init:
      mode: always
      data-locations: classpath:db/script.sql
