spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:hsqldb:mem:translate
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    sql:
      init:
        schema-locations: classpath:db/script.sql
        mode: always
